# -*- mode: python ; coding: utf-8 -*-
# Windows 打包仅使用 OneFile：生成单个 exe，运行时解压到 %TEMP%。

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'core',
        'core.models',
        'core.loaders',
        'core.matching',
        'core.embedding',
        'core.utils',
        'core.utils.excel_io',
        'core.utils.similarity',
        'core.config',
        'core.config.paths',
        'core.config.llm',
        'core.config.mcp',
        'llm',
        'llm.client',
        'llm.llm_config',
        'llm.prompt',
        'mcp_client',
        'app',
        'app.batch_match',
        'app.file_io',
        'paths',
        'rapidfuzz',
        'openai',
        'torch',
        'torch.nn',
        'torch.nn.functional',
        'sentence_transformers',
        'transformers',
        'modelscope',
        'numpy',
        'openpyxl',
        'tqdm',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', '_tkinter',
        'matplotlib', 'matplotlib.pyplot',
        'PIL', 'Pillow',
        'pytest', '_pytest', 'test', 'tests',
        'IPython', 'jupyter', 'notebook', 'nbformat',
        'sphinx', 'docutils',
        'cv2', 'opencv',
        'pandas',
    ],
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CategoryMatching',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
